version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: grouppay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: grouppay
      POSTGRES_USER: grouppay
      POSTGRES_PASSWORD: grouppay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grouppay"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
